language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev
  - sudo apt-get install maven
install: 
  - make
  - make python
  - cd java; mvn test
script: make test
